services:
  - type: web
    name: paves-chatbot
    env: python
    repo: https://github.com/Jagadish-Pannala/jagadish
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: LANGCHAIN_API_KEY
        value: off
      - key: LANGCHAIN_TRACING_V2
        value: false
      - key: LANGCHAIN_ENDPOINT
        value: ""

